export let countries = [
  {countryCode: 'AFG', name: 'Afghanistan', countryCode2: 'AF'},
  {countryCode: 'ALA', name: 'Åland', countryCode2: 'AX'},
  {countryCode: 'ALB', name: 'Albania', countryCode2: 'AL'},
  {countryCode: 'DZA', name: 'Algeria', countryCode2: 'DZ'},
  {countryCode: 'ASM', name: 'American Samoa', countryCode2: 'AS'},
  {countryCode: 'AND', name: 'Andorra', countryCode2: 'AD'},
  {countryCode: 'AGO', name: 'Angola', countryCode2: 'AO'},
  {countryCode: 'AIA', name: 'Anguilla', countryCode2: 'AI'},
  {countryCode: 'ATA', name: 'Antarctica', countryCode2: 'AQ'},
  {countryCode: 'ATG', name: 'Antigua and Barbuda', countryCode2: 'AG'},
  {countryCode: 'ARG', name: 'Argentina', countryCode2: 'AR'},
  {countryCode: 'ARM', name: 'Armenia', countryCode2: 'AM'},
  {countryCode: 'ABW', name: 'Aruba', countryCode2: 'AW'},
  {countryCode: 'AUS', name: 'Australia', countryCode2: 'AU'},
  {countryCode: 'AUT', name: 'Austria', countryCode2: 'AT'},
  {countryCode: 'AZE', name: 'Azerbaijan', countryCode2: 'AZ'},
  {countryCode: 'BHS', name: 'Bahamas', countryCode2: 'BS'},
  {countryCode: 'BHR', name: 'Bahrain', countryCode2: 'BH'},
  {countryCode: 'BGD', name: 'Bangladesh', countryCode2: 'BD'},
  {countryCode: 'BRB', name: 'Barbados', countryCode2: 'BB'},
  {countryCode: 'BLR', name: 'Belarus', countryCode2: 'BY'},
  {countryCode: 'BEL', name: 'Belgium', countryCode2: 'BE'},
  {countryCode: 'BLZ', name: 'Belize', countryCode2: 'BZ'},
  {countryCode: 'BEN', name: 'Benin', countryCode2: 'BJ'},
  {countryCode: 'BMU', name: 'Bermuda', countryCode2: 'BM'},
  {countryCode: 'BTN', name: 'Bhutan', countryCode2: 'BT'},
  {countryCode: 'BOL', name: 'Bolivia', countryCode2: 'BO'},
  {countryCode: 'BES', name: 'Bonaire', countryCode2: 'BQ'},
  {countryCode: 'BIH', name: 'Bosnia and Herzegovina', countryCode2: 'BA'},
  {countryCode: 'BWA', name: 'Botswana', countryCode2: 'BW'},
  {countryCode: 'BVT', name: 'Bouvet Island', countryCode2: 'BV'},
  {countryCode: 'BRA', name: 'Brazil', countryCode2: 'BR'},
  {countryCode: 'IOT', name: 'British Indian Ocean Territory', countryCode2: 'IO'},
  {countryCode: 'VGB', name: 'British Virgin Islands', countryCode2: 'VG'},
  {countryCode: 'BRN', name: 'Brunei', countryCode2: 'BN'},
  {countryCode: 'BGR', name: 'Bulgaria', countryCode2: 'BG'},
  {countryCode: 'BFA', name: 'Burkina Faso', countryCode2: 'BF'},
  {countryCode: 'BDI', name: 'Burundi', countryCode2: 'BI'},
  {countryCode: 'KHM', name: 'Cambodia', countryCode2: 'KH'},
  {countryCode: 'CMR', name: 'Cameroon', countryCode2: 'CM'},
  {countryCode: 'CAN', name: 'Canada', countryCode2: 'CA'},
  {countryCode: 'CPV', name: 'Cape Verde', countryCode2: 'CV'},
  {countryCode: 'CYM', name: 'Cayman Islands', countryCode2: 'KY'},
  {countryCode: 'CAF', name: 'Central African Republic', countryCode2: 'CF'},
  {countryCode: 'TCD', name: 'Chad', countryCode2: 'TD'},
  {countryCode: 'CHL', name: 'Chile', countryCode2: 'CL'},
  {countryCode: 'CHN', name: 'China', countryCode2: 'CN'},
  {countryCode: 'CXR', name: 'Christmas Island', countryCode2: 'CX'},
  {countryCode: 'CCK', name: 'Cocos [Keeling] Islands', countryCode2: 'CC'},
  {countryCode: 'COL', name: 'Colombia', countryCode2: 'CO'},
  {countryCode: 'COM', name: 'Comoros', countryCode2: 'KM'},
  {countryCode: 'COK', name: 'Cook Islands', countryCode2: 'CK'},
  {countryCode: 'CRI', name: 'Costa Rica', countryCode2: 'CR'},
  {countryCode: 'HRV', name: 'Croatia', countryCode2: 'HR'},
  {countryCode: 'CUB', name: 'Cuba', countryCode2: 'CU'},
  {countryCode: 'CUW', name: 'Curacao', countryCode2: 'CW'},
  {countryCode: 'CYP', name: 'Cyprus', countryCode2: 'CY'},
  {countryCode: 'CZE', name: 'Czech Republic', countryCode2: 'CZ'},
  {countryCode: 'COD', name: 'Democratic Republic of the Congo', countryCode2: 'CD'},
  {countryCode: 'DNK', name: 'Denmark', countryCode2: 'DK'},
  {countryCode: 'DJI', name: 'Djibouti', countryCode2: 'DJ'},
  {countryCode: 'DMA', name: 'Dominica', countryCode2: 'DM'},
  {countryCode: 'DOM', name: 'Dominican Republic', countryCode2: 'DO'},
  {countryCode: 'TLS', name: 'East Timor', countryCode2: 'TL'},
  {countryCode: 'ECU', name: 'Ecuador', countryCode2: 'EC'},
  {countryCode: 'EGY', name: 'Egypt', countryCode2: 'EG'},
  {countryCode: 'SLV', name: 'El Salvador', countryCode2: 'SV'},
  {countryCode: 'GNQ', name: 'Equatorial Guinea', countryCode2: 'GQ'},
  {countryCode: 'ERI', name: 'Eritrea', countryCode2: 'ER'},
  {countryCode: 'EST', name: 'Estonia', countryCode2: 'EE'},
  {countryCode: 'ETH', name: 'Ethiopia', countryCode2: 'ET'},
  {countryCode: 'FLK', name: 'Falkland Islands', countryCode2: 'FK'},
  {countryCode: 'FRO', name: 'Faroe Islands', countryCode2: 'FO'},
  {countryCode: 'FJI', name: 'Fiji', countryCode2: 'FJ'},
  {countryCode: 'FIN', name: 'Finland', countryCode2: 'FI'},
  {countryCode: 'FRA', name: 'France', countryCode2: 'FR'},
  {countryCode: 'GUF', name: 'French Guiana', countryCode2: 'GF'},
  {countryCode: 'PYF', name: 'French Polynesia', countryCode2: 'PF'},
  {countryCode: 'ATF', name: 'French Southern Territories', countryCode2: 'TF'},
  {countryCode: 'GAB', name: 'Gabon', countryCode2: 'GA'},
  {countryCode: 'GMB', name: 'Gambia', countryCode2: 'GM'},
  {countryCode: 'GEO', name: 'Georgia', countryCode2: 'GE'},
  {countryCode: 'DEU', name: 'Germany', countryCode2: 'DE'},
  {countryCode: 'GHA', name: 'Ghana', countryCode2: 'GH'},
  {countryCode: 'GIB', name: 'Gibraltar', countryCode2: 'GI'},
  {countryCode: 'GRC', name: 'Greece', countryCode2: 'GR'},
  {countryCode: 'GRL', name: 'Greenland', countryCode2: 'GL'},
  {countryCode: 'GRD', name: 'Grenada', countryCode2: 'GD'},
  {countryCode: 'GLP', name: 'Guadeloupe', countryCode2: 'GP'},
  {countryCode: 'GUM', name: 'Guam', countryCode2: 'GU'},
  {countryCode: 'GTM', name: 'Guatemala', countryCode2: 'GT'},
  {countryCode: 'GGY', name: 'Guernsey', countryCode2: 'GG'},
  {countryCode: 'GIN', name: 'Guinea', countryCode2: 'GN'},
  {countryCode: 'GNB', name: 'Guinea-Bissau', countryCode2: 'GW'},
  {countryCode: 'GUY', name: 'Guyana', countryCode2: 'GY'},
  {countryCode: 'HTI', name: 'Haiti', countryCode2: 'HT'},
  {countryCode: 'HMD', name: 'Heard Island and McDonald Islands', countryCode2: 'HM'},
  {countryCode: 'HND', name: 'Honduras', countryCode2: 'HN'},
  {countryCode: 'HKG', name: 'Hong Kong', countryCode2: 'HK'},
  {countryCode: 'HUN', name: 'Hungary', countryCode2: 'HU'},
  {countryCode: 'ISL', name: 'Iceland', countryCode2: 'IS'},
  {countryCode: 'IND', name: 'India', countryCode2: 'IN'},
  {countryCode: 'IDN', name: 'Indonesia', countryCode2: 'ID'},
  {countryCode: 'IRN', name: 'Iran', countryCode2: 'IR'},
  {countryCode: 'IRQ', name: 'Iraq', countryCode2: 'IQ'},
  {countryCode: 'IRL', name: 'Ireland', countryCode2: 'IE'},
  {countryCode: 'IMN', name: 'Isle of Man', countryCode2: 'IM'},
  {countryCode: 'ISR', name: 'Israel', countryCode2: 'IL'},
  {countryCode: 'ITA', name: 'Italy', countryCode2: 'IT'},
  {countryCode: 'CIV', name: 'Ivory Coast', countryCode2: 'CI'},
  {countryCode: 'JAM', name: 'Jamaica', countryCode2: 'JM'},
  {countryCode: 'JPN', name: 'Japan', countryCode2: 'JP'},
  {countryCode: 'JEY', name: 'Jersey', countryCode2: 'JE'},
  {countryCode: 'JOR', name: 'Jordan', countryCode2: 'JO'},
  {countryCode: 'KAZ', name: 'Kazakhstan', countryCode2: 'KZ'},
  {countryCode: 'KEN', name: 'Kenya', countryCode2: 'KE'},
  {countryCode: 'KIR', name: 'Kiribati', countryCode2: 'KI'},
  {countryCode: 'XKX', name: 'Kosovo', countryCode2: 'XK'},
  {countryCode: 'KWT', name: 'Kuwait', countryCode2: 'KW'},
  {countryCode: 'KGZ', name: 'Kyrgyzstan', countryCode2: 'KG'},
  {countryCode: 'LAO', name: 'Laos', countryCode2: 'LA'},
  {countryCode: 'LVA', name: 'Latvia', countryCode2: 'LV'},
  {countryCode: 'LBN', name: 'Lebanon', countryCode2: 'LB'},
  {countryCode: 'LSO', name: 'Lesotho', countryCode2: 'LS'},
  {countryCode: 'LBR', name: 'Liberia', countryCode2: 'LR'},
  {countryCode: 'LBY', name: 'Libya', countryCode2: 'LY'},
  {countryCode: 'LIE', name: 'Liechtenstein', countryCode2: 'LI'},
  {countryCode: 'LTU', name: 'Lithuania', countryCode2: 'LT'},
  {countryCode: 'LUX', name: 'Luxembourg', countryCode2: 'LU'},
  {countryCode: 'MAC', name: 'Macao', countryCode2: 'MO'},
  {countryCode: 'MKD', name: 'Macedonia', countryCode2: 'MK'},
  {countryCode: 'MDG', name: 'Madagascar', countryCode2: 'MG'},
  {countryCode: 'MWI', name: 'Malawi', countryCode2: 'MW'},
  {countryCode: 'MYS', name: 'Malaysia', countryCode2: 'MY'},
  {countryCode: 'MDV', name: 'Maldives', countryCode2: 'MV'},
  {countryCode: 'MLI', name: 'Mali', countryCode2: 'ML'},
  {countryCode: 'MLT', name: 'Malta', countryCode2: 'MT'},
  {countryCode: 'MHL', name: 'Marshall Islands', countryCode2: 'MH'},
  {countryCode: 'MTQ', name: 'Martinique', countryCode2: 'MQ'},
  {countryCode: 'MRT', name: 'Mauritania', countryCode2: 'MR'},
  {countryCode: 'MUS', name: 'Mauritius', countryCode2: 'MU'},
  {countryCode: 'MYT', name: 'Mayotte', countryCode2: 'YT'},
  {countryCode: 'MEX', name: 'Mexico', countryCode2: 'MX'},
  {countryCode: 'FSM', name: 'Micronesia', countryCode2: 'FM'},
  {countryCode: 'MDA', name: 'Moldova', countryCode2: 'MD'},
  {countryCode: 'MCO', name: 'Monaco', countryCode2: 'MC'},
  {countryCode: 'MNG', name: 'Mongolia', countryCode2: 'MN'},
  {countryCode: 'MNE', name: 'Montenegro', countryCode2: 'ME'},
  {countryCode: 'MSR', name: 'Montserrat', countryCode2: 'MS'},
  {countryCode: 'MAR', name: 'Morocco', countryCode2: 'MA'},
  {countryCode: 'MOZ', name: 'Mozambique', countryCode2: 'MZ'},
  {countryCode: 'MMR', name: 'Myanmar [Burma]', countryCode2: 'MM'},
  {countryCode: 'NAM', name: 'Namibia', countryCode2: 'NA'},
  {countryCode: 'NRU', name: 'Nauru', countryCode2: 'NR'},
  {countryCode: 'NPL', name: 'Nepal', countryCode2: 'NP'},
  {countryCode: 'NLD', name: 'Netherlands', countryCode2: 'NL'},
  {countryCode: 'NCL', name: 'New Caledonia', countryCode2: 'NC'},
  {countryCode: 'NZL', name: 'New Zealand', countryCode2: 'NZ'},
  {countryCode: 'NIC', name: 'Nicaragua', countryCode2: 'NI'},
  {countryCode: 'NER', name: 'Niger', countryCode2: 'NE'},
  {countryCode: 'NGA', name: 'Nigeria', countryCode2: 'NG'},
  {countryCode: 'NIU', name: 'Niue', countryCode2: 'NU'},
  {countryCode: 'NFK', name: 'Norfolk Island', countryCode2: 'NF'},
  {countryCode: 'PRK', name: 'North Korea', countryCode2: 'KP'},
  {countryCode: 'MNP', name: 'Northern Mariana Islands', countryCode2: 'MP'},
  {countryCode: 'NOR', name: 'Norway', countryCode2: 'NO'},
  {countryCode: 'OMN', name: 'Oman', countryCode2: 'OM'},
  {countryCode: 'PAK', name: 'Pakistan', countryCode2: 'PK'},
  {countryCode: 'PLW', name: 'Palau', countryCode2: 'PW'},
  {countryCode: 'PSE', name: 'Palestine', countryCode2: 'PS'},
  {countryCode: 'PAN', name: 'Panama', countryCode2: 'PA'},
  {countryCode: 'PNG', name: 'Papua New Guinea', countryCode2: 'PG'},
  {countryCode: 'PRY', name: 'Paraguay', countryCode2: 'PY'},
  {countryCode: 'PER', name: 'Peru', countryCode2: 'PE'},
  {countryCode: 'PHL', name: 'Philippines', countryCode2: 'PH'},
  {countryCode: 'PCN', name: 'Pitcairn Islands', countryCode2: 'PN'},
  {countryCode: 'POL', name: 'Poland', countryCode2: 'PL'},
  {countryCode: 'PRT', name: 'Portugal', countryCode2: 'PT'},
  {countryCode: 'PRI', name: 'Puerto Rico', countryCode2: 'PR'},
  {countryCode: 'QAT', name: 'Qatar', countryCode2: 'QA'},
  {countryCode: 'COG', name: 'Republic of the Congo', countryCode2: 'CG'},
  {countryCode: 'REU', name: 'Réunion', countryCode2: 'RE'},
  {countryCode: 'ROU', name: 'Romania', countryCode2: 'RO'},
  {countryCode: 'RUS', name: 'Russia', countryCode2: 'RU'},
  {countryCode: 'RWA', name: 'Rwanda', countryCode2: 'RW'},
  {countryCode: 'BLM', name: 'Saint Barthélemy', countryCode2: 'BL'},
  {countryCode: 'SHN', name: 'Saint Helena', countryCode2: 'SH'},
  {countryCode: 'KNA', name: 'Saint Kitts and Nevis', countryCode2: 'KN'},
  {countryCode: 'LCA', name: 'Saint Lucia', countryCode2: 'LC'},
  {countryCode: 'MAF', name: 'Saint Martin', countryCode2: 'MF'},
  {countryCode: 'SPM', name: 'Saint Pierre and Miquelon', countryCode2: 'PM'},
  {countryCode: 'VCT', name: 'Saint Vincent and the Grenadines', countryCode2: 'VC'},
  {countryCode: 'WSM', name: 'Samoa', countryCode2: 'WS'},
  {countryCode: 'SMR', name: 'San Marino', countryCode2: 'SM'},
  {countryCode: 'STP', name: 'São Tomé and Príncipe', countryCode2: 'ST'},
  {countryCode: 'SAU', name: 'Saudi Arabia', countryCode2: 'SA'},
  {countryCode: 'SEN', name: 'Senegal', countryCode2: 'SN'},
  {countryCode: 'SRB', name: 'Serbia', countryCode2: 'RS'},
  {countryCode: 'SYC', name: 'Seychelles', countryCode2: 'SC'},
  {countryCode: 'SLE', name: 'Sierra Leone', countryCode2: 'SL'},
  {countryCode: 'SGP', name: 'Singapore', countryCode2: 'SG'},
  {countryCode: 'SXM', name: 'Sint Maarten', countryCode2: 'SX'},
  {countryCode: 'SVK', name: 'Slovakia', countryCode2: 'SK'},
  {countryCode: 'SVN', name: 'Slovenia', countryCode2: 'SI'},
  {countryCode: 'SLB', name: 'Solomon Islands', countryCode2: 'SB'},
  {countryCode: 'SOM', name: 'Somalia', countryCode2: 'SO'},
  {countryCode: 'ZAF', name: 'South Africa', countryCode2: 'ZA'},
  {countryCode: 'SGS', name: 'South Georgia and the South Sandwich Islands', countryCode2: 'GS'},
  {countryCode: 'KOR', name: 'South Korea', countryCode2: 'KR'},
  {countryCode: 'SSD', name: 'South Sudan', countryCode2: 'SS'},
  {countryCode: 'ESP', name: 'Spain', countryCode2: 'ES'},
  {countryCode: 'LKA', name: 'Sri Lanka', countryCode2: 'LK'},
  {countryCode: 'SDN', name: 'Sudan', countryCode2: 'SD'},
  {countryCode: 'SUR', name: 'Suriname', countryCode2: 'SR'},
  {countryCode: 'SJM', name: 'Svalbard and Jan Mayen', countryCode2: 'SJ'},
  {countryCode: 'SWZ', name: 'Swaziland', countryCode2: 'SZ'},
  {countryCode: 'SWE', name: 'Sweden', countryCode2: 'SE'},
  {countryCode: 'CHE', name: 'Switzerland', countryCode2: 'CH'},
  {countryCode: 'SYR', name: 'Syria', countryCode2: 'SY'},
  {countryCode: 'TWN', name: 'Taiwan', countryCode2: 'TW'},
  {countryCode: 'TJK', name: 'Tajikistan', countryCode2: 'TJ'},
  {countryCode: 'TZA', name: 'Tanzania', countryCode2: 'TZ'},
  {countryCode: 'THA', name: 'Thailand', countryCode2: 'TH'},
  {countryCode: 'TGO', name: 'Togo', countryCode2: 'TG'},
  {countryCode: 'TKL', name: 'Tokelau', countryCode2: 'TK'},
  {countryCode: 'TON', name: 'Tonga', countryCode2: 'TO'},
  {countryCode: 'TTO', name: 'Trinidad and Tobago', countryCode2: 'TT'},
  {countryCode: 'TUN', name: 'Tunisia', countryCode2: 'TN'},
  {countryCode: 'TUR', name: 'Turkey', countryCode2: 'TR'},
  {countryCode: 'TKM', name: 'Turkmenistan', countryCode2: 'TM'},
  {countryCode: 'TCA', name: 'Turks and Caicos Islands', countryCode2: 'TC'},
  {countryCode: 'TUV', name: 'Tuvalu', countryCode2: 'TV'},
  {countryCode: 'UMI', name: 'U.S. Minor Outlying Islands', countryCode2: 'UM'},
  {countryCode: 'VIR', name: 'U.S. Virgin Islands', countryCode2: 'VI'},
  {countryCode: 'UGA', name: 'Uganda', countryCode2: 'UG'},
  {countryCode: 'UKR', name: 'Ukraine', countryCode2: 'UA'},
  {countryCode: 'ARE', name: 'United Arab Emirates', countryCode2: 'AE'},
  {countryCode: 'GBR', name: 'United Kingdom', countryCode2: 'GB'},
  {countryCode: 'USA', name: 'United States', countryCode2: 'US'},
  {countryCode: 'URY', name: 'Uruguay', countryCode2: 'UY'},
  {countryCode: 'UZB', name: 'Uzbekistan', countryCode2: 'UZ'},
  {countryCode: 'VUT', name: 'Vanuatu', countryCode2: 'VU'},
  {countryCode: 'VAT', name: 'Vatican City', countryCode2: 'VA'},
  {countryCode: 'VEN', name: 'Venezuela', countryCode2: 'VE'},
  {countryCode: 'VNM', name: 'Vietnam', countryCode2: 'VN'},
  {countryCode: 'WLF', name: 'Wallis and Futuna', countryCode2: 'WF'},
  {countryCode: 'ESH', name: 'Western Sahara', countryCode2: 'EH'},
  {countryCode: 'YEM', name: 'Yemen', countryCode2: 'YE'},
  {countryCode: 'ZMB', name: 'Zambia', countryCode2: 'ZM'},
  {countryCode: 'ZWE', name: 'Zimbabwe', countryCode2: 'ZW'}
]

export default countries;
